// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantmanagementSystem.Data;

#nullable disable

namespace RestaurantmanagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230524043829_CreateRestaurantTable")]
    partial class CreateRestaurantTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("RestaurantmanagementSystem.Modals.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("restaurant_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("type_of_cusine")
                        .HasColumnType("TEXT");

                    b.Property<string>("type_of_food")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
